name: Python compiler windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v1
      with:
        submodules: 'true'
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install pyinstaller
    - name: python version
      run: python --version
    - name: pyinstaller version
      run: pyinstaller --version
    
    - name: run SSTslicer directly
      run: python .\src\SSTslicer.py -v
    
    - name: compile SSTslicer
      run: pyinstaller -F .\src\SSTslicer.py
      
    - name: run compiled version
      run: .\dist\SSTslicer.exe -v

    - name: save compiled files
      uses: actions/upload-artifact@master
      with:
        name: SSTslicer_windows
        path: .\dist
